name: Terraform CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP_NAME: "my-resource-group"
  LOCATION: "canadacentral"
  APIM_NAME: "my-apim-instance"
  PUBLISHER_NAME: "Aspiringakashdp"
  PUBLISHER_EMAIL: "Aspiringakashdp@gmail.com"
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          audience: api://AzureADTokenExchange

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan \
            -var="resource_group_name=${{ env.RESOURCE_GROUP_NAME }}" \
            -var="location=${{ env.LOCATION }}" \
            -var="apim_name=${{ env.APIM_NAME }}" \
            -var="publisher_name=${{ env.PUBLISHER_NAME }}" \
            -var="publisher_email=${{ env.PUBLISHER_EMAIL }}" \
            -var="jwt_secret=${{ env.JWT_SECRET }}" \
            -out=tfplan
        continue-on-error: false

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: your-github-username

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply tfplan